
on: [pull_request]
name: License check
env:
  GO111MODULE: on 
  
  license-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: make license

      - name: license updated check
        run: git diff --exit-code